### ISSUE TITLE
Critical bug)

### ISSUE THREAD

**Issue by Sergei-Alekseev** [fjdogar/multicore_rom_helper#2]
Hello)
Now problem with snes roms.
Here is screenshot of glitch.
![_____glitch2222](https://github.com/user-attachments/assets/99b1ac48-e4dd-4ca6-881f-f8c6d8c7ada9)
Looks like only roms with picture with the same name can be processed.
All roms without partner picture brings error.
Nevermind selected placeholder image or not.

**Comment by Sergei-Alekseev** [comment]
No i was wrong) Everything is messed up.
Look at sreenshot what exactly is created.
![____gllll](https://github.com/user-attachments/assets/46c6d346-2319-464d-a919-bdf21db8cc54)
Some roms processed.
And pictures)

**Comment by fjdogar** [comment]
Thanks for pointing that out. I thought i fixed this issue ,but apparently not . ill review the code and try to figure out whats happening. can you plz zip this folder (with roms and pngs) amd send it to me  , i wanna recreate the issue . dm me the file on discord plz if you can

**Comment by Sergei-Alekseev** [comment]
Some files from directory:
[snes.zip](https://github.com/user-attachments/files/17083753/snes.zip)
arcana and area88 was created properly, other *.smc - error, links to *.png created instead of roms.

**Comment by fjdogar** [comment]
please download and try the latest release , i have fixed the issues

**Comment by Sergei-Alekseev** [comment]
Thank you.
Some things related:
can you please add an option to strip rom extension from result?
I mean Arcana.smc --> Arcana.zfb
I dont need extensions in rom list personally)
Renaming it manually is not fun process.

When starting from zfb, option sf2000_scaling_mode = "full screen" doesnt apply from Snes9x 2002.opt file.
If starting from user list option applied correctly.

**Comment by fjdogar** [comment]
I actually need the rom extension to be in the filename for some cases.

But i guess it shoudnt be default behaviour and should be added as an extra setting to keep rom extension. 

As for the opt file, it has to be a multicore thing,  having different behavior for Stock Rom and User Rom. MRH has nothing to do with game loading. 

EDIT
Make sure you are not using different cores for stubs and zfb, that's the only possible reason its behaving this way

Thanks for your feedback, I'll make these changes
